### ISSUE TITLE
Separate IPEDS flags by post-graduate year

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#1]
It is not appropriate to have a single IPEDS flags for the all-cohort rollup, since the values can be different across the PGYs.

**Comment by srt1** [comment]
done

**Comment by srt1** [comment]
It looks like I had an older version of this file in the schema

**Comment by srt1** [comment]
Measure names/descriptions awaiting comment/signoff - @heathhayward @andrewfoote @jodyhoonstarr 

(and Joyce)

**Comment by jodyhoonstarr** [comment]
FYI for all: If files get added to the master branch they get auto built into the new "draft" docs assuming that you made changes to the latest version (V4.7.0). Changes to older ones (e.g. V4.5.0-draft) need to be run manually. 

So the changes Stephen just made can be seen here:
https://ledapplications.github.io/lehd-schema/formats/V4.7.0/lehd_public_use_schema.html#_post_secondary_employment_outcomes_earnings_pseoe

**Comment by srt1** [comment]
Nice!
________________________________

**Comment by andrewfoote** [comment]
Signed off by me - those variable names/descriptions look good.

**Comment by srt1** [comment]
#1, #2 

The measure tables are ready to go, but I want to give @heathhayward a final chance to comment on whether the _"Indicator Name"_ and _"Descripton"_ meet the requirements of the application. 

Note, the XML labels used for the CEDSCI API are kept in a separate variable on the internal control table, and are not formally part of the schema. Right now the XML labels match the variable description exactly, but they can be modified independently, if needed.

**Comment by heathhayward** [comment]
Once the issue in https://github.com/LEDApplications/lehd-schema/issues/2 is resolved, this ticket can be closed as well.

**Comment by srt1** [comment]
I got a message "commit failed" for my last change, but it looks like it took. Closing out.
