### ISSUE TITLE
Broken links to www.census.gov/geo/reference/

### ISSUE THREAD

**Issue by julfers** [LEDApplications/DEPRECATED-lehd-schema#10]
Links to https://www.census.gov/geo/reference/ are broken (404). For example https://www.census.gov/geo/reference/codes/cou.html

Links appear in https://lehd.ces.census.gov/data/schema/j2j_latest/lehd_shapefiles.html, for example, but also a number of other places including csv files, so this might be a large find/replace job.

Relates to #9

**Comment by jodyhoonstarr** [comment]
List to check by hand:

https://lehd.ces.census.gov/data/)  404
https://www.census.gov/cgi-bin/sssd/naics/naicsrch?chart=2017.  503
https://ifap.ed.gov/ifap/fedSchoolCodeList.jsp  404
https://www.digitalpreservation.gov/formats/fdd/fdd000280.shtml  000
https://www.digitalpreservation.gov/formats/fdd/fdd000280.shtml  000
https://www.census.gov/geo/reference/codes/cou.html  500
https://www.census.gov/geo/reference/ansi_statetables.html)  500
https://www.census.gov/population/metro/data/def.html)  500

**Comment by jodyhoonstarr** [comment]
Update links

- https://www.census.gov/geo/reference/ansi_statetables.html  (status: 503)
  - replace https://www.census.gov/library/reference/code-lists/ansi/ansi-codes-for-states.html
- https://www.census.gov/population/metro/data/def.html  (status: 503)
  - replace https://www.census.gov/programs-surveys/metro-micro.html
- https://www.digitalpreservation.gov/formats/fdd/fdd000280.shtml  (status: 000)
  - replace https://www.loc.gov/preservation/digital/formats/fdd/fdd000280.shtml
- https://www.census.gov/geo/reference/codes/cou.html  (status: 500)
  - replace https://www.census.gov/library/reference/code-lists/ansi/ansi-codes-for-states.html
