### ISSUE TITLE
6.13.2 - update display table to show additional fields?

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#14]
The label_institution.csv contains the following fields:

`institution,label,city,institution_state,inst_level,statefips
`

The sample in 6.13.2 displays only 

`institution,label,institution_state
`

We may want to add a few more fields, or all, if space permits. Thoughts?

**Comment by andrewfoote** [comment]
@srt1 What other fields were you thinking? It does seem that we should have all the fields, instead of the restricted in the sample.

**Comment by srt1** [comment]
All of the fields would be fine with me, if there isn't a display issue with table width.

We might also want to identify a better set of institutions for display purposes. Allocating 7 lines to divisions, which we don't even tabulate on at this time, and then displaying 8 records of Faulkner University in Alabama is perhaps an odd selection.
________________________________

**Comment by andrewfoote** [comment]
@jodyhoonstarr we should at least have city and state. 

Also, seconding @srt1 that the example is weird, because of Faulkner University. I had no idea there were so many.

**Comment by andrewfoote** [comment]
Schools to include: (@jodyhoonstarr )

University of Colorado Boulder
University of Texas - Austin
Ohio State University
University of Michigan (00232500)
University of Wisconsin - Madison
Pennsylvania State University (00332900)

**Comment by srt1** [comment]
@andrewfoote  - The US Dept of Ed link is broken, of course. Can you find an appropriate non-broken link?

**Comment by srt1** [comment]
I will close this issue, and open up the broken link as a separate issue. It is annoying enough on its own to not be included in this.
