### ISSUE TITLE
Grad Cohort/Years variables text (6.16, 6.17)

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#15]
The boxes under 6.16 an 6.17 are a little awkward and confusing. And there is a bit of a variance with some of the earlier convention, where the actual variable name was in the heading (note the lack of underscores in the headings of 6.16 and 6.17.  This convention is not carried through in the industry/industry level, so there have been exceptions in the past. We should be sure, though, to include the actual variable name in the description, if it is not the heading - particularly because these variables do not have csv tables associated with them.

### 6.16 Grad Cohort

*Grad_Cohort*  is a 4-digit number representing the first year of the graduation cohort. The number of years in the cohort is reported in the separate Grad Cohort Years variable.

_Text Box- Should we put an "e.g." to denote this is an example?_

`e.g., If grad_cohort is 2010 and grad_cohort_years is 3, ...`

### 6.17 Grad Cohort Years

*Grad_Cohort_Years* is the number of years in the cohort of reference (see *Grad_Cohort*). It varies by degree_level.

The "otherwise" should appear on a new line. I'd stick a semicolon at the end of the first phrase.

`If degree_level=05, then grad_cohort_years=3 (3 year cohorts for bachelor's degrees);
otherwise, grad_cohort_years=5 (5 year cohorts for all other degrees).`

_ALTERNATIVELY_

Get rid of the text box in 6.17, modify the text as follows;

This is the number of years in the cohort of reference (see Grad Cohort). It varies by **degree_level**. Bachelor's degrees (05) are reported in 3 year cohorts, all other degrees are reported in 5 year cohorts. The **grad_cohort_years** will take a value (3,5). As tabulations are not done across degree types, the appropriate value will be reported in **grad_cohort_years** when **grad_cohort**=0000.

**Comment by jodyhoonstarr** [comment]
I made a few tweaks here. It looked like variables should be monospace text but I'm happy to swap the formatting to italics, bold, etc.

**Comment by srt1** [comment]
Good enough, thanks.
