### ISSUE TITLE
Geo division descriptions? (6.18.2)

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#16]
I think this has come up before, but wanted to make sure we have a good answer:

I don't think that the schema tells the user what states comprise each division. (And amazingly, there are still people out there who can't rattle off the 7 states in "West North Central.")  If we don't add the division to one of the state tables, is there a good link we can provide users? The best one I can find is:

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf

Or we can just let users Google it themselves. Let me know what you think - again, I guess.

**Comment by andrewfoote** [comment]
@srt1 I think linking to that division map is the best idea, under 6.18.2

**Comment by srt1** [comment]
I had a hard time finding the text you added referencing the map. I would suggest instead placing it in the next section, where the divisions are described, rather than the states. Everyone knows what states are. People who need more added detail will probably be looking for descriptions of the division, so it seems more natural to provide that reference there. 

`The file label_geography_division.csv contains values and labels for all entities of geo_level 'D'. For more information on which states comprise each division, see the map here.`

**Comment by srt1** [comment]
Done
