### ISSUE TITLE
6.13.2 Correct link to source of institution list (6.13.2) - currently pointing to the old table, and also broken

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#18]
The Department of Education has weird .jsp links to its pages, which rarely work several months (or weeks) down the road.

The link https://ifap.ed.gov/ifap/fedSchoolCodeList.jsp is now broken. It is also an old link, which has a 6-digit OPEID. It is the link noted in the `FedSchool_readin.sas` program. 

The input table with the 8-digit OPEID can be found here:

https://www2.ed.gov/offices/OSFAP/PEPS/downloadfiles/Schoolfile/schfile.zip

This is not an ideal link for the schema, however, as it goes right to a download, rather than any documentation about the file. 

@andrewfoote, if you can find a more useful link, that would be great.

**Comment by andrewfoote** [comment]
@srt1 

This is the link that takes you to the link to download: https://www2.ed.gov/offices/OSFAP/PEPS/dataextracts.html

From there, it is somewhat unclear what to download unless we add additional instructions to the effect of "Download the School File under option 1" (the other files are also the same data, but for Microsoft Access which...not a lot of people use)

**Comment by srt1** [comment]
That link is fine. Jody, please update with this link.

Thanks.
________________________________

**Comment by srt1** [comment]
Done
