### ISSUE TITLE
Add "unobserved" variables to flows data

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#2]
Separate variables will be set up for protected counts of that are not observed in the earnings data (formerly "ZZ" flows). The ZZ/Z will no longer appear as a state or industry.

```
y1_grads_nme
y5_grads_nme
y10_grads_nme
```

**Comment by srt1** [comment]
Measure names/descriptions awaiting comment/signoff - @heathhayward @andrewfoote @jodyhoonstarr 

(and Joyce)

**Comment by andrewfoote** [comment]
@srt1 Also signing off on this. Thanks for this change - it makes so much more sense than our original.

**Comment by srt1** [comment]
#1, #2 

The measure tables are ready to go, but I want to give @heathhayward a final chance to comment on whether the _"Indicator Name"_ and _"Descripton"_ meet the requirements of the application. 

Note, the XML labels used for the CEDSCI API are kept in a separate variable on the internal control table, and are not formally part of the schema. Right now the XML labels match the variable description exactly, but they can be modified independently, if needed.

**Comment by heathhayward** [comment]
In https://ledapplications.github.io/lehd-schema/formats/V4.7.0/variables_pseoe.csv, the "Description" field needs the "(2016 Dollars)" text removed from y1_grads_earn.  Otherwise the names and descriptions look good.

**Comment by srt1** [comment]
variables_pseo.csv is corrected, closing out.
