### ISSUE TITLE
9.2 - changes from previous version

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#21]
I'm not sure how much detail is traditionally put into section 9.2, but the comment on merging PSEO is pretty spare. I'd recommend adding the following (if it's not considered too much - haven't really reviewed to figure out what the convention is):

* Changes from 4.6.0
  *  Merge PSEO schema files into official release version
  * Minor formatting changes

* Changes from 4.5.0-draft
  * Institution identifier changed from 6 to  8-digit code
  * CIPCODE reported using 2020 coding
  * Additional status flags on PSEO Earnings
  * Additional measures on PSEO Flows to report unobserved/marginally employed
  * Earnings reported at 2-digit CIPCODE level

_Anything else significant I forgot?_

**Comment by srt1** [comment]
Oh, yes, these two are big - I just added the 8-digit institution code and 2020 CIPCODE to the bulleted list (previous comment).

**Comment by jodyhoonstarr** [comment]
The 8-digit inst and 2020 cip are now included. I forgot to tag the commit to this issue.

**Comment by srt1** [comment]
good enough, thanks
