### ISSUE TITLE
Validate/Update Versions and Dates

### ISSUE THREAD

**Issue by jodyhoonstarr** [LEDApplications/DEPRECATED-lehd-schema#22]
Check and update superseded versions and date timestamps if needed.

**Comment by srt1** [comment]
I see - I didn't realize what this ticket was intended for. I will include the comment listed in #23, and close that.

- [ ]  Please indicate that V4.7.0 will be used in 2020Q4 production
V 4.6.0 is still valid for QWI/J2J for 2020Q3. PSEO isn't really part of the quarterly release schedule.

- [ ] On the [file naming page](https://ledapplications.github.io/lehd-schema/formats/V4.7.0/lehd_csv_naming.html#_changes), the "Changes from ..." section can be trimmed down (assuming no other technical reason not to):

### Changes from 4.6.0

    Adding PSEO data product

**Comment by jodyhoonstarr** [comment]
Did you still want all the stuff in the 4.5.0-draft changes? Or clear that out too?

> Changes from 4.5.0-draft
> - Additional status flags on PSEO Earnings
> - Additional measures on PSEO Flows to report unobserved/marginally employed
> - Earnings reported at 2-digit CIPCODE level
> - Institution code changed to 8-digits
> - Updated to 2020 CIPCODE

**Comment by srt1** [comment]
Those changes are relevant for the primary schema page, but not relevant for the "file naming convention" page. And I think you could say that we added those naming convention changes in 4.5.0-draft, so there is effectively no difference between 4.5.0-draft and 4.7.0. So what we want to say here is that we are incorporating the PSEO changes from the draft into the official branch - so it's changes from 4.6.0.
________________________________

**Comment by srt1** [comment]
The only reason to keep them would have been if the "changes from" was static, and could not be vary across the different pages. If it has to be the same, keep the whole thing. If it can vary, make it relevant for the page you are looking at.
________________________________

**Comment by srt1** [comment]
... at least, that's what makes sense to me. I didn't design the system, so I sometimes have to infer the intent, and don't always get it right.
________________________________

**Comment by jodyhoonstarr** [comment]
Right now there's a single static changes.txt that gets tacked onto the end of every page. We can split it out to individual files easily if we care to detail the changelist for each section. It takes minimal technical effort, the only question is whether we want to maintain it.
- changes_schema.txt
- changes_naming.txt
- changes_shapefiles.txt

**Comment by srt1** [comment]
Your call. Not a big deal, then.
________________________________

**Comment by srt1** [comment]
Heath the other primary owner of this, and I generally don't like to specify those kind of structural changes without his input, so I can happily table it.
________________________________

**Comment by heathhayward** [comment]
I'm happy with whatever solution is the easiest to maintain going forward. I agree that it's a bit weird to mention shapefile changes on the "naming" page, but the changes section refers to schema version changes, not page changes. But if it's easy to maintain separate change files, then I'm down with that approach.

**Comment by srt1** [comment]
It's likely that for the majority of schema version updates, there will be no change to the "naming conventions" page - so the "changes from" for that page would be blank, if we made the section independent from the primary schema page. So presumably, someone would have to remember to update it. If we think we can maintain separate sections, we can do that; otherwise, keep it as-is.

Thanks.

________________________________

**Comment by jodyhoonstarr** [comment]
Split out files can be seen here (clear your cache if they all look the same):
- [main schema](https://ledapplications.github.io/lehd-schema/formats/V4.7.0/lehd_public_use_schema.html#_changes)
- [shapefiles](https://ledapplications.github.io/lehd-schema/formats/V4.7.0/lehd_shapefiles.html#_changes)
- [naming](https://ledapplications.github.io/lehd-schema/formats/V4.7.0/lehd_csv_naming.html#_changes)

Feel free to request any changes to the items seen there.

**Comment by srt1** [comment]
That all looks fine to me. I don't follow the shapefiles one, so fill that in as appropriate. If it's the same as 4.6.0, you can probably put "No changes" or "None."

I'll sign off on 4.7.0 - feel free to push to the website whenever you are ready. Thanks for putting this all together.
________________________________

**Comment by heathhayward** [comment]
Yep, this is fine as it is.
