### ISSUE TITLE
Sundry edits/questions

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#23]
Just looking through:

* Is the _"This specification is draft"_ tab going to come off in the final build?

* Section 4. Supersedes
  * Should be "for files released as of R2020Q3," I think?

* In https://ledapplications.github.io/lehd-schema/formats/V4.7.0/lehd_csv_naming.html
  * Section 8. Changes
    * Should this repeat all of the changes from 4.6.0/4.5.0-draft? It seems that this should simply report the changes for this page. I would simply mention:

###  Changes from 4.6.0
 * Adding PSEO data product

**Comment by srt1** [comment]
Camille has requested that the schema number doesn't change for quarterly 2020Q3 production. We should indicate that the schema should be used beginning 2020Q4. The PSEO isn't tied to release quarters the same way, so it's OK if this is a little different. I guess.

We could probably describe what the releases mean for a product like PSEO - it's really not quite clear. I'm not worrying about that now.

**Comment by jodyhoonstarr** [comment]
The way it works is that any commits that get autobuilt by github (e.g. when a file gets uploaded or changed) get the draft text. When we're ready to push it out the door we'll run a manual build on master. I've done this in testing so you can see the difference by looking at the top box in the [draft build](https://github.com/LEDApplications/lehd-schema/blob/gh-pages/formats/V4.7.0/lehd_public_use_schema.asciidoc) vs the [master build](https://github.com/LEDApplications/lehd-schema/blob/master/formats/V4.7.0/lehd_public_use_schema.asciidoc).

I'm going go go through and update the dates/text issues in https://github.com/LEDApplications/lehd-schema/issues/22

Will update the changes text you noted.

**Comment by srt1** [comment]
Check
________________________________

**Comment by srt1** [comment]
Duplicative of #22
