### ISSUE TITLE
CIP Level Doc Changes

### ISSUE THREAD

**Issue by jodyhoonstarr** [LEDApplications/DEPRECATED-lehd-schema#24]
Since the user needs to filter, or at least generally understand, the two and four digit CIP codes we should add a bit of text and reference material to the schemadocs. Put any relevant links/refs in this ticket.

**Comment by andrewfoote** [comment]
Dumb question - can we just say "2-digit Series" and "4-digit Series"? 

That is how they are referred to here: https://nces.ed.gov/ipeds/cipcode/Files/CIP_Help_Document_2020.pdf

**Comment by srt1** [comment]
That's a question for the application team. My sense is that they wanted to have something less jargony, perhaps, to those who don't know what a CIP code is. I don't really care, myself.
________________________________

**Comment by jodyhoonstarr** [comment]
Yeah, that's right - less jargony. The 2-digit/4-digit text works but then needs some explanation of what a series is. Here's the text from [ed](https://nces.ed.gov/ipeds/cipcode/Default.aspx?y=56) that we can use verbatim. Maybe just an example of one 2 digit cip and all it's 4-dight children is good enough for the schema. 

> What is the CIP?
> The Classification of Instructional Programs (CIP) provides a taxonomic scheme that supports the accurate tracking and reporting of fields of study and program completions activity.

**Comment by srt1** [comment]
2-digit and 4-digit is fine for the schema. Since we don't have any useful terms from Ed to go on ("family" doesn't cut it), how about something like:


  *   2-digit: Area of study
  *   4-digit: Degree field

________________________________

**Comment by srt1** [comment]
.. or "Area of instruction" and "degree field"?

The app should make it reasonably obvious that by these terms we mean 2-digit and 4-digit (hover-over, help button, whatever)

________________________________

**Comment by srt1** [comment]
BTW, I was just looking at the Cornell website this morning, and was inspired by our motto:

“I would found an institution where any person can find instruction in any study.”

-Ezra Cornell
________________________________

**Comment by srt1** [comment]
And the unofficial follow up:

Andrew Dickson White: "But Ezra, that sounds great, but then everyone will want to come there."

Ezra: Not where I'm going to put it.
________________________________

**Comment by jodyhoonstarr** [comment]
I'm not entirely sure it's obvious in userland what the practical differences between 2 digit and 4 digit cips are without exploring the data. Closing this for now since the cip level has the 2 vs 4 digit text and I'm not entirely sure how this could be made clear in either the app or schema via text.
