### ISSUE TITLE
Shapefiles reference old geography

### ISSUE THREAD

**Issue by jodyhoonstarr** [LEDApplications/DEPRECATED-lehd-schema#25]
The shapefiles page appears to have been pulled from the 4.5 draft rather than the 4.6 updates.

**Comment by jodyhoonstarr** [comment]
Retag with 4.7.0 once done.

**Comment by heathhayward** [comment]
do you know whether the label files in 4.7.0 came from 4.50 or 4.6.0?

**Comment by jodyhoonstarr** [comment]
Most files started as 4.6.0 and then some got overwritten/modified when 4.5.0 was changes were merged. New label changes came from Stephen in some cases. Looking at the [directory](https://github.com/LEDApplications/lehd-schema/tree/master/formats/V4.7.0) shows a column with the latest commit message. The 4.6 ones say "Create V4.7.0 from V4.6.0".
