### ISSUE TITLE
Delete refs to XX cipcodes

### ISSUE THREAD

**Issue by jodyhoonstarr** [LEDApplications/DEPRECATED-lehd-schema#27]
Following our discussion on PSEO to remove these aggregates we should scrub the 4.7.0 schema for all references to anything XX.

**Comment by srt1** [comment]
add sub-sub-sub section:

### 6.19.2.1 Restricted 4-digit CIP tabulations in earnings data (PSEOE)

Earnings estimates and counts are provided only at the 2-digit CIP level for Masters and Doctor Research programs (degree levels 07 and 17). Records are included for 4-digit programs observed, but all measures are suppressed.

**Comment by srt1** [comment]
@jodyhoonstarr  - additional mod for this section:

In **6.19.1**, delete text _"agg_level is currently reported only for J2J data products."_

Add section:
### 6.19.3 QWI
Aggregation level to be added to QWI in a future release

**Comment by srt1** [comment]
I think these changes are ready to go. Let me know when they are ready, or if there are any suggested modifications.

**Comment by srt1** [comment]
@jodyhoonstarr

Sorry, forgot to mention this one. In section 6.15.2, remove the following sentence:

_In 4-digit CIP tabulations, select degree levels are collapsed to the 2-Digit CIP family, using custom codes (e.g., 01.XX, 02.XX, etc.)._

**Comment by jodyhoonstarr** [comment]
Changes: 6.19.2 has a subsection but it doesn't get labeled or shown in the TOC:
https://ledapplications.github.io/lehd-schema/formats/V4.7.0/lehd_public_use_schema.html#_pseo

6.19.1 had the line delted and 6.19.3 was added for QWI:
https://ledapplications.github.io/lehd-schema/formats/V4.7.0/lehd_public_use_schema.html#_qwi

6.15.2 had the sentence removed:
https://ledapplications.github.io/lehd-schema/formats/V4.7.0/lehd_public_use_schema.html#_cip_codes

**Comment by srt1** [comment]
Hmm... without a proper heading, that comment on the 4-digit CIP codes looks to be in no-man's land; but I don't know if it particularly makes sense to move it up above that table.

Andrew, do you have any thoughts? Heath?
________________________________

**Comment by jodyhoonstarr** [comment]
Give it a sec to rebuild, it should now show as a subsubsub heading.

**Comment by andrewfoote** [comment]
So it has a subsubsub heading, but no associated number for TOC? I think that works fine, as long as it is there to reference.

**Comment by jodyhoonstarr** [comment]
Now it's got a number 6.19.2.1 and a link. If you cant see it either disable/clear your browser cache or open another one:

https://ledapplications.github.io/lehd-schema/formats/V4.7.0/lehd_public_use_schema.html#_restricted_4_digit_cip_tabulations_in_earnings_data_pseoe

**Comment by srt1** [comment]
Thanks. That's a little awkward, perhaps, with all the sub-levels, but it stands out a bit. I'm OK with that, unless anyone has any better ideas. Good enough for me.

________________________________

**Comment by jodyhoonstarr** [comment]
Cool. Will get this pulled internally and wrap up 4.7.0
