### ISSUE TITLE
More info on PSEO on file name conventions

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#29]
Section 5.2 should add PSEO, since the version_*txt file is there for that, as well.

We should add some detail about what the years mean for PSEO - did we do that anywhere else?

**Comment by heathhayward** [comment]
PSEO is covered in 5.2: https://lehd.ces.census.gov/data/schema/V4.7.0/lehd_public_use_schema.html#_identifiers_for_pseo. Not sure I understand this ticket.

**Comment by srt1** [comment]
Sorry, this 5.2:

https://lehd.ces.census.gov/data/schema/V4.7.0/lehd_csv_naming.html#_metadata_for_qwi_and_j2j_data_files_version_txt

This heading should also mention PSEO.

We may also want to mention here that the year range in PSEO indicate the graduation years - but that may not be necessary.
________________________________

**Comment by heathhayward** [comment]
Not sure its necessary. I vote we simply add "PSEO" to the 5.2. heading and close the issue

**Comment by andrewfoote** [comment]
I don't think the year ranges comment is necessary either. I agree with @heathhayward

**Comment by srt1** [comment]
OK, once PSEO is added to the heading of 5.2, we can close.
