### ISSUE TITLE
Generate working branch 4.7.0

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#3]
Merge branches 4.5.0-draft (PSEO) with 4.6..0 (2019 geo, latest J2J mods). We will use 4.7.0 to add the latest modifications to the PSEO schema for the next release.

i.e., I need a place to put the updated schema csv files.

**Comment by jodyhoonstarr** [comment]
There's a new branch for this (V4.7.0). Because of the structure of this repo it's a little bit of a pain to apply the 4.5.0 changes. Will pencil it in, along with the travisci build steps, for next week.

**Comment by jodyhoonstarr** [comment]
I always forget how confusing the structure of this repo is... for clarity there's both a V4.7.0 branch and a formats/V4.7.0 directory. Swap to the branch and to the folder to drop files.
