### ISSUE TITLE
Change EmpSpv availability - not in latest quarter

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#30]
Section 8.3 - Metadata on indicator availability (lags_qwi.csv)

The variable EmpSpv line should be changed to (2,1).

This change is being brought about because of the restructuring of the QWI weights. While the stable-previous quarter conceptually can exist in the last quarter of data, it serves no purpose. It exists to complete the full quarter job-flow identity, and the other components of that are not calculable in the last quarter. 

This measure is calculated to complete the identity mentioned above, using the new method. There is no point in creating an alternate method to calculate it in the last quarter. So, we should just change the availability range.

**Comment by heathhayward** [comment]
[lags_qwi.zip](https://github.com/LEDApplications/lehd-schema/files/5857443/lags_qwi.zip)

**Comment by jodyhoonstarr** [comment]
Updated file and v4.8 schema can be seen [here](https://ledapplications.github.io/lehd-schema/formats/V4.8.0/lehd_public_use_schema.html#_metadata_on_indicator_availability)
