### ISSUE TITLE
Updated label_institution.csv for March 2021 PSEO

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#32]
We have a new version of label_institution for the next PSEO release. This file was hand-edited in redmine ticket 3201.

**Comment by andrewfoote** [comment]
Is someone else going to pull in the label_institution.csv, or should I do it? Not sure how to do any of this.

**Comment by srt1** [comment]
I think we can just load the new file into the right path on Github - once Jody says it's ready. But you don't need to get in the middle of that - I can do it.
________________________________

**Comment by andrewfoote** [comment]
Let the issue ticket record state that Stephen knows I will somehow mess it up in unfixable ways.

**Comment by heathhayward** [comment]
Can this issue be closed?

**Comment by srt1** [comment]
I had left it open in case Andrew had any other edits to label_institution, besides the one fix it CT. I'm assuming not, so hereby closed.
