### ISSUE TITLE
Add geography bullet to list of changes in main Schema page

### ISSUE THREAD

**Issue by heathhayward** [LEDApplications/DEPRECATED-lehd-schema#35]
Please add one more bullet to the bottom of http://lehdweb.dev.ces.census.gov/data/schema/V4.8.0/lehd_public_use_schema.html#_changes_from_4_7_0:

- Underlying geovintage updated to reflect 2020 TIGER/Line geography - except for CBSAs. Tabulations for "B" and "M" geo_levels continue to use 2019 TIGER/Line geographies.

**Comment by jodyhoonstarr** [comment]
Looks good to me: https://ledapplications.github.io/lehd-schema/formats/V4.8.0/lehd_public_use_schema.html#_changes_from_4_7_0

**Comment by srt1** [comment]
The explanation is a little esoteric for the user who just needs to slap a label on a region, but it's fine. I'm sure this is correct. If any users are befuddled, they can do more research, or contact us.

Thanks.
________________________________

**Comment by jodyhoonstarr** [comment]
Yeah, we can beef it up if needed. Chuck in tickets here as issues come up and we can fill out the sections.
