### ISSUE TITLE
Add PSU Global Campus to label_institution

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#38]
We are creating a separate OPEID (institution number) for PSU Global Campus. We may want to make a comment that we have made some custom edits to the PEPS data, to indicate this is not exactly what we retrieve from them

This will be included in the "maintenance release" of PSEO, Summer 2021

Schema V4.8.1?

**Comment by jodyhoonstarr** [comment]
Confirmed "Penn State World Campus" found in label file
