### ISSUE TITLE
Inconsistent encodings in csv files

### ISSUE THREAD

**Issue by julfers** [LEDApplications/DEPRECATED-lehd-schema#39]
Some of the csv files, such as https://lehd.ces.census.gov/data/schema/V4.8.0/label_agegrp.csv are encoded as UTF-8 with BOM, while others, such as https://lehd.ces.census.gov/data/schema/V4.8.0/variables_j2j.csv are encoded as UTF-8 without BOM.

It would be better to use a consistent encoding for all csv files, preferably utf-8 without bom.

This is a backward and forward compatible change *if* the client was reading the file correctly, that is, dropping the byte order mark *if and only if* it's present. That will likely depend on what library the client used to read the files. For example, [in Python](https://docs.python.org/3.8/library/codecs.html#encodings-and-unicode), if clients were using the `utf-8` encoding instead of `utf-8-sig`, they will read an extra character at the beginning of some files:

```
>>> with open('label_agegrp.csv', encoding='utf-8-sig') as f:
...     next(f)
...
'agegrp,label\n'
>>> with open('label_agegrp.csv', encoding='utf-8') as f:
...     next(f)
...
'\ufeffagegrp,label\n'
```

When rendered, the extra character may be invisible due to how the [Unicode consortium suggests handling it](https://www.unicode.org/faq/utf_bom.html#bom6):

> Q: What should I do with U+FEFF in the middle of a file?
> 
> A: In the absence of a protocol supporting its use as a BOM and when not at the beginning of a text stream, U+FEFF should normally not occur. For backwards compatibility it should be treated as ZERO WIDTH NON-BREAKING SPACE (ZWNBSP)…

The files with a byte order mark may have come from Excel. For historical reasons, Excel adds a bom when saving a file as "CSV UTF-8 (Comma delimited)."

**Comment by jodyhoonstarr** [comment]
TODO on my end: add pre-publication check for encoding issues. Don't fix, warn.

**Comment by jodyhoonstarr** [comment]
We talked about notifying data producers rather than fixing but that was impossibly annoying. All csv data files are now passed through the standard `dos2unix` command before schema publication.
