### ISSUE TITLE
Change PSEO earnings to 2019 dollars

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#42]
We will be publishing the R2021Q3 release of PSEO in 2019 dollars. The labels on variables_pseo.csv need to be modified to say 2019.

**Comment by srt1** [comment]
@jodyhoonstarr, I think that the 4.8.1 milestone needs to be closed out. Please create a new 4.8.2 version for the next PSEO release, at your convenience.

Practically, I don't know what digit in the schema number should be changing here. Nothing changes in the output tables, at all - but it is a meaningful difference in what the reported dollars represent. It's hard to get inside the mind of Lars to know how we should be changing the schema numbers, in that case...

**Comment by jodyhoonstarr** [comment]
Created a new milestone for V4.8.2, created a new directory under formats for 4.8.2 , then rolled back the changes from Andrews file in 4.8.1. The 2019 pseoe variable change can be seen in the new directory [here](https://github.com/LEDApplications/lehd-schema/blob/master/formats/V4.8.2/variables_pseoe.csv).

**Comment by srt1** [comment]
Thanks @jodyhoonstarr, looks good.
