### ISSUE TITLE
IPEDS - add flag to indicate incomplete roll-ups

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#43]
Adjust the IPEDS business rules for the higher-level aggregations

Currently if any lower level cells are unavailable in IPEDS, the higher level IPEDS counts are suppressed. This can create lots of suppressions at the higher level, even if only very small counts are affected.

We will add a value 4 to the IPEDS status flags to indicate that the IPEDS is an aggregation where some of the cohorts/programs were missing IPEDS data (i.e., caveat emptor).

Also, review the text in the IPEDS status flag section to determine if we can better describe this issue.

**Comment by heathhayward** [comment]
Cool, this should be easy. We just need to add a row to the CSV. Let me know what language you'd like to see for flag '4'. Plus any changes to:

Graduate counts are provided from public use data from the[ Integrated Postsecondary Education Data System (IPEDS)](https://nces.ed.gov/ipeds/use-the-data). Counts are linked to graduation cohorts in the PSEO data and included in the PSEOE tables. In a small number of cases, misalignment in programs (CIPCODE) is observed between the IPEDS and PSEO counts. In these cases, the IPEDS counts adjusted to be consistent with those on PSEO, and the count is flagged accordingly.

**Comment by andrewfoote** [comment]
How about this for the flag text:

"IPEDS counts partially missing"

**Comment by andrewfoote** [comment]
And to @heathhayward's point, we could add a sentence that says "When aggregating across programs and years, IPEDS counts are flagged accordingly when one or more programs are missing."

**Comment by srt1** [comment]
_I have edited the status flag description here. Please also add status flag 4, as Andrew describes.  Thanks._

7.2. IPEDS Count Status Flag

( label_flags_ipeds_count.csv )

Graduate counts associated with PSEO earnings tabulations are provided using public use data from the Integrated Postsecondary Education Data System (IPEDS). Counts are linked to graduation cohorts in the PSEO data and included in the PSEOE tables. In a small number of cases, misalignment in programs (CIPCODE) is observed between the IPEDS and PSEO counts. In these cases, the IPEDS counts are adjusted to be consistent with those on PSEO, and the count is flagged accordingly. For higher level aggregations (e.g., all cohorts, all CIPCODE), IPEDS totals may sum over cohorts or programs for which graduate counts were not available. The counts are released but flagged to indicate missing data. IPEDS counts may be suppressed and flagged as not available in some cases when PSEO earnings data do not meet Census Bureau publication standards.

```
flag,label
1,IPEDS counts as reported 
2,IPEDS counts edited for consistency with PSEO categories
3,IPEDS counts not available
4,IPEDS counts partially missing
```

**Comment by heathhayward** [comment]
[label_flags_ipeds_count.csv](https://github.com/LEDApplications/lehd-schema/files/7211308/label_flags_ipeds_count.csv)

**Comment by srt1** [comment]
Just manually edited it in the release - hope I did it right...

**Comment by jodyhoonstarr** [comment]
Looks right to me: https://ledapplications.github.io/lehd-schema/formats/V4.8.2/lehd_public_use_schema.html#_ipeds_count_status_flag
