### ISSUE TITLE
Update to CIP 2020

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#7]
The 2020 CIP codes are available, schema needs to be updated

**Comment by andrewfoote** [comment]
Full list of CIP codes is here: https://nces.ed.gov/ipeds/cipcode/resources.aspx?y=56

Their website is java based I think, so I can't give exact URLs because of course.

**Comment by srt1** [comment]
Ooh - both Excel and Word download. Which to choose? Both so convenient.

**Comment by srt1** [comment]
CIPCODEs for 2020, for 4.7.0 release.

Please update text in **6.15.2** to indicate codes are in 2020, rather than 2020.

[label_cipcode2020.zip](https://github.com/LEDApplications/lehd-schema/files/4495179/label_cipcode2020.zip)

**Comment by srt1** [comment]
Update text in 6.15.12 to read _"2020 CIP Codes"_

**Comment by srt1** [comment]
Sample table in 6.15.2 is empty - only a few ellipses.

**Comment by jodyhoonstarr** [comment]
Re: 6.15.2 empty table 
Hmm, this one works locally but fails when github builds it. Looking into what's going on.

**Comment by srt1** [comment]
@jodyhoonstarr  - the heading should not say "2020" - the reference is in the text below it, as below (do not incorporate bold into final version)


**6.15.2. CIP Code**

( label_cipcode.csv )

CIP codes are sourced from the National Center for Education Statistics (NCES), Integrated Postsecondary Education Data System (IPEDS). Data are reported using **2020** CIP codes, for all years. In 4-digit CIP tabulations, select degree levels are collapsed to the 2-Digit CIP family, using custom codes (e.g., 01.XX, 02.XX, etc.).

**Comment by jodyhoonstarr** [comment]
That was a silly one.

**Comment by srt1** [comment]
With @andrewfoote, reviewed the file to confirm it contains new 2020 codes, and not retired 2010 codes. It looks good, I'm signing off.
