### ISSUE TITLE
Correct cipcodes on 4.5.0-draft

### ISSUE THREAD

**Issue by srt1** [LEDApplications/DEPRECATED-lehd-schema#8]
For CIPCODES that transitioned, the schema file kept the old, rather than new code. This mostly affected 6-digit codes, which are not published in PSEO, but it should be corrected. The one 4-digit code that was affected was 40.10, was 14,31 (Materials Science). This CIP only appeared in the data at the PhD level, which is effectively tabulated at the 2-digit level, so it was not noticed. 

The old schema should be corrected with the replacement file.

**Comment by srt1** [comment]
This file should replace label_cipcode.csv on 4.5.0-draft. It contains CIPs in 2010.
If possible, a note could be added to the bottom of the schema to mention that this file has been corrected.

[label_cipcode2010.zip](https://github.com/LEDApplications/lehd-schema/files/4495168/label_cipcode2010.zip)

**Comment by jodyhoonstarr** [comment]
Do we want to keep the 4.5.0-draft schema? There was a note that said draft schemas will be deleted when they are superseded or something like that so I created [issue #19](https://github.com/LEDApplications/lehd-schema/issues/19).

**Comment by srt1** [comment]
Do not remove this draft schema, since it is referenced in tables produced in a public release. Same with some of the earlier J2J draft schemas - they should persist and be accessible. Did Lars make a comment at some point about deleting draft schemas? That could not apply if we actually published on that. What note are you referencing? Someone may need to explain what "draft" means...
________________________________

**Comment by jodyhoonstarr** [comment]
Maybe we just need to call it V4.5.0 and remove the "-draft" text and call it published? There was a note in the readme that said
`Draft V4.5.0 version (will be removed once released).`

**Comment by srt1** [comment]
News to me. The version.txt files reference 4.5.0-draft, not 4.5.0.
We have several draft versions in the 4.1 range - there were never any instructions to change that.
I wouldn't change anything until someone tells me what the rationale/proper procedure is.
________________________________

**Comment by jodyhoonstarr** [comment]
This can be seen:
https://ledapplications.github.io/lehd-schema/formats/V4.5.0-draft/lehd_public_use_schema.html#_cip_code

**Comment by srt1** [comment]
Done
